export const KPI_PRESETS = [
  {
    id: 'revenue-quarter',
    name: 'Revenue This Quarter',
    label: 'Revenue This Quarter',
    source_type: 'integration' as const,
    query_config: {
      endpoint: 'deals',
      filter: { stage: 'closedwon', period: 'quarter' },
      aggregate: 'sum',
      field: 'amount',
    },
    format: 'currency',
    currency: 'CAD',
    show_trend: true,
    trend_period: 'quarter',
    refresh_seconds: 300,
  },
  {
    id: 'deals-closed',
    name: 'Deals Closed',
    label: 'Deals Closed',
    source_type: 'integration' as const,
    query_config: {
      endpoint: 'deals',
      filter: { stage: 'closedwon', period: 'quarter' },
      aggregate: 'count',
      field: 'id',
    },
    format: 'number',
    currency: 'CAD',
    show_trend: true,
    trend_period: 'quarter',
    refresh_seconds: 300,
  },
  {
    id: 'new-clients',
    name: 'New Clients',
    label: 'New Clients',
    source_type: 'integration' as const,
    query_config: {
      endpoint: 'companies',
      filter: { period: 'quarter' },
      aggregate: 'count',
      field: 'id',
    },
    format: 'number',
    currency: 'CAD',
    show_trend: true,
    trend_period: 'quarter',
    refresh_seconds: 300,
  },
  {
    id: 'pipeline-value',
    name: 'Pipeline Value',
    label: 'Pipeline Value',
    source_type: 'integration' as const,
    query_config: {
      endpoint: 'deals',
      filter: { stage: 'open' },
      aggregate: 'sum',
      field: 'amount',
    },
    format: 'currency',
    currency: 'CAD',
    show_trend: true,
    trend_period: 'quarter',
    refresh_seconds: 300,
  },
] as const
