export const CELEBRATION_PRESETS = [
  {
    id: 'deal-won',
    name: 'Deal Won',
    title_pattern: '🎉 DEAL WON!',
    subtitle_pattern: '{{owner_name}} closed {{deal_name}}',
    visual_style: 'confetti',
    sound: 'victory',
    duration_seconds: 20,
    show_counter: false,
    show_photos: true,
  },
  {
    id: 'new-client',
    name: 'New Client',
    title_pattern: '🤝 NEW CLIENT!',
    subtitle_pattern: '{{company_name}}',
    visual_style: 'fireworks',
    sound: 'victory',
    duration_seconds: 20,
    show_counter: false,
    show_photos: true,
  },
  {
    id: 'subscription',
    name: 'Subscription',
    title_pattern: '⭐ NEW SUBSCRIBER!',
    subtitle_pattern: '{{customer_name}} subscribed',
    visual_style: 'champagne',
    sound: 'cash_register',
    duration_seconds: 20,
    show_counter: false,
    show_photos: true,
  },
  {
    id: 'contract-signed',
    name: 'Contract Signed',
    title_pattern: '✍️ CONTRACT SIGNED!',
    subtitle_pattern: '{{owner_name}} closed {{deal_name}}',
    visual_style: 'confetti',
    sound: 'bell',
    duration_seconds: 20,
    show_counter: false,
    show_photos: true,
  },
  {
    id: 'renewal',
    name: 'Renewal',
    title_pattern: '🔄 RENEWAL SIGNED!',
    subtitle_pattern: '{{company_name}} renewed',
    visual_style: 'confetti',
    sound: 'cash_register',
    duration_seconds: 20,
    show_counter: false,
    show_photos: true,
  },
  {
    id: 'custom-milestone',
    name: 'Custom Milestone',
    title_pattern: '🏆 {{title}}',
    subtitle_pattern: '{{subtitle}}',
    visual_style: 'confetti',
    sound: 'bell',
    duration_seconds: 20,
    show_counter: false,
    show_photos: true,
  },
] as const

export type PresetId = (typeof CELEBRATION_PRESETS)[number]['id']
